# Generated by Django 2.1.3 on 2018-11-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
    ]
