# Generated by Django 2.1.3 on 2018-11-28 04:54

import auction.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category_list',
        ),
        migrations.AddField(
            model_name='auction',
            name='isFlagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=auction.models.get_image_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='auction',
            name='categories',
            field=models.ManyToManyField(to='auction.Category'),
        ),
    ]
